name: Automatically limit
on: 
  schedule:
    - cron: "*/5 * * * *"
jobs:
  limiter:
    runs-on: ubuntu-latest
    steps:
    - name: Do the curl
      run: |
          curl --request PUT \
          --url https://api.github.com/repos/${{ github.repository }}/interaction-limits \
          --header 'authorization: Bearer ${{ secrets.REPO_MANAGER }}' \
          --header 'content-type: application/json' \
          --header 'Accept: application/vnd.github.sombra-preview' \
          --data '{
            "limit": "collaborators_only"
          }'
